### ISSUE TITLE
Does not throw error on invalid address

### ISSUE THREAD

**Issue by cliffhall** [cryptocoinjs/eip55#2]
I was trying to validate an ethereum address form field with `eip55.verify(eip55.encode(address))`. 

I noticed that anything exactly 42 characters is passes.

<img width="542" alt="Screen Shot 2020-12-17 at 3 05 53 PM" src="https://user-images.githubusercontent.com/871933/102537763-5f5bbc00-4079-11eb-805f-6e52f562afdb.png">

Also, **another weird thing** about the above screenshot is that the initial `verify` fails, but the second one succeeds when the result is encoded first. However the `verify` function in `eip55` itself runs the address it is given through `encode` first, so my `eip55.verify(eip55.encode(address))` actually should not be required. 

Maybe it could be considered out of scope (e.g., _"The eip55 package should only be concerned with length and case"_), but it would be really useful if it could also validate that the characters fall in the right range (i.e., "0x" in first 2 characters, [a-f,A-F,0-9] for characters 2-42. It can be done like this:`address.match(/^0x[a-fA-F0-9]{40}$/i)`).

**Comment by cliffhall** [comment]
@dcousens I will be glad to submit a pull request if you're still maintaining this project.

**Comment by junderw** [comment]
I went ahead and fixed the issue in #3 

@cliffhall if you could review it for me, I will merge it.

1. verify doesn't throw, only returns false if not string / doesn't match the EIP-55 format (including 0x)
2. encode is much stricter, requiring a 40 length hex string with/without a leading 0x (Previously only checked if length was 42)

**Comment by junderw** [comment]
also, FYI, `eip55.verify(eip55.encode(address))` is useless since encode will always output a valid EIP-55 address (or it should, the current code is broken) so verify will always be true.

**Comment by junderw** [comment]
If you want to accept a normal non-EIP-55 address as valid, you can do something like this. (Makes sure that
```js
function verifyAddress(address) {
    if (address.match(/^0x([0-9a-f]{40}|[0-9A-F]{40})$/)) {
        return true
    } else {
        return eip55.verify(address)
    }
}
```

![スクリーンショット_2020-12-18_18-47-00](https://user-images.githubusercontent.com/11246316/102599880-72e25200-4161-11eb-9873-eb7f21af31bf.png)
