### ISSUE TITLE
Typo in an address example provided

### ISSUE THREAD

**Issue by antonio-fr** [cryptocoinjs/eip55#7]
Not a big deal, but the example provided in the documentation is wrong.
```
eip55.verify('0xAcA128edBD274F2aBa534d67dD55Ebf67767B9A5')
// => true
```
But actually this is => false.
The correct is `0xAcA128edBD274F2aBa534d67DD55Ebf67767B9A5`
notice the DD55 instead of dD55.

I just checked against the latest package 2.1.0 version, and it is not a bug in the library. Just a typo in the documentation. Quite ironic as this library goal is to check if there's a typo in an Ethereum address. And one provided example is plain wrong.

**Comment by junderw** [comment]
:laughing: :rofl: 

Thanks for the catch!

**Comment by antonio-fr** [comment]
You're welcome. I was hunting for some [EIP55 testing data for Uniblow](https://github.com/bitlogik/uniblow/blob/master/tests/test_addresses.py#L96). Because the EIP55 standard is very poor regarding test vectors. And this address gave me some hard times. My first thought was there could be an issue in [our EIP55 implementation](https://github.com/bitlogik/uniblow/blob/master/wallets/ETHwallet.py#L222).
